spring.application.name=final

server.servlet.context-path=/final
server.port=9001

#mvc


#datasource
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

#hikari
spring.datasource.hikari.pool-name=TestHikariPool
spring.datasource.hikari.minimum-idle=50
spring.datasource.hikari.connection-timeout=5000
spring.datasource.hikari.connection-init-sql=SELECT 1
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.max-lifetime=1800000


#mybatis
mybatis.type-aliases-package=com.ssafy.passproject.domain.**.entity
mybatis.mapper-locations=classpath:/mapper/*.xml
mybatis.configuration.auto-mapping-behavior=FULL
mybatis.type-handlers-package=com.ssafy.passproject.handler

#spring secret
#??? ??????.
spring.jwt.secret=${SPRING_JWT_SECRET}

# TourAPI ì¤ì 
# encode key
tour.api.servicekey=${TOUR_API_SERVICEKEY}
# decode key
#tour.api.service-key=${TOUR_API_SERVICEKEY}
api.base-url=https://apis.data.go.kr/B551011/KorService2/locationBasedList2

weather.api.base-url=https://apis.data.go.kr/1360000/VilageFcstInfoService_2.0

# kakao API
kakao.rest.api.key=${KAKAO_REST_API_KEY}

# mail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${SPRING_MAIL_USERNAME}
spring.mail.password=${SPRING_MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
